from python_graphql_client import GraphqlClient

graphql_client = GraphqlClient(endpoint="http://localhost:4000/graphql/core",headers={'Authorization':'ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmhjSEJKYm1adklqcDdJbTVoYldVaU9pSjBaV3RwWlZSdGN5SXNJblI1Y0dVaU9pSnpkR0YwYVdNaWZTd2lhV0YwSWpveE5UZzVOVE13T0RVNExDSmxlSEFpT2pFNU1EVXhNRFk0TlRoOS43ck9ILW5fM2Z1dUR0TWFoTVdJUVhOQS1nejllX216Y0o5VlNOTHd1WmVvOjpleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKMWMyVnlTVzVtYnlJNmV5SnBaQ0k2SW1OcmVEZHdlbWc1YmpBd00zb3dkREZvWTNGaU1tUjZjbU1pTENKMWMyVnlibUZ0WlNJNklrOXRSSFZpWlhsNWVTSjlMQ0pwWVhRaU9qRTJOalUyT0RFd05Ua3NJbVY0Y0NJNk1UWTVOekl6T0RZMU9YMC5NUjZfQkV3SWx3Y3JfWGFwU3RtaHlWNjM4NjNITDctN3ltQlNkSHBDbm9F'})

# wrapper for fetching data
def fetchData(query,variables = {}):
    data = graphql_client.execute(query=query,variables=variables)
    return data
